using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BobbingAnimation : MonoBehaviour
{
    public float fequency;
    public float magnitude;
    public Vector3 direction;
    Vector3 initialPosition;
    Pickup pickup;

    private void Start()
    {
        pickup = GetComponent<Pickup>();    

        initialPosition = transform.position;
    }

    private void Update()
    {
        if(pickup && !pickup.hasBeenCollected)
        {
            transform.position = initialPosition + direction * Mathf.Sin(Time.time * fequency) * magnitude;
        }
        
    }
}
